namespace SigOpsMetrics.API.Classes
{
    public class ApiDescription
    {
        public const string Description = @"
<h2>API serving new.SigOpsMetrics.com</h2>
<br />
<p>
  This API allows for the querying of  data on the new.SigOpsMetrics.com site. Some data
  is available for export via the ExportMetrics controller to a
  a comma-separated value (csv) file format, which can be opened in Excel. This
  page explains how to structure a query as a url. It also provides an
  interactive way to use the API to download data.
</p>
<br />
<table>
  <thead>
    <tr>
      <th>Measure</th>
      <th>Description</th>
      <th>cor/qhr</th>
      <th>cor/hr</th>
      <th>cor/dy</th>
      <th>cor/mo</th>
      <th>cor/qu</th>
      <th>cor/wk</th>
      <th>sig/qhr</th>
      <th>sig/hr</th>
      <th>sig/dy</th>
      <th>sig/mo</th>
      <th>sig/wk</th>
      <th>sub/qhr</th>
      <th>sub/hr</th>
      <th>sub/dy</th>
      <th>sub/mo</th>
      <th>sub/qu</th>
      <th>sub/wk</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>cctv</td>
      <td>CCTV Uptime (%)</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>cu</td>
      <td>Communications Uptime (%)</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>du</td>
      <td>Detector Uptime (%)</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>pau</td>
      <td>Pedestrian Actuation/Pushbutton Uptime (%)</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>tasks</td>
      <td>TEAMS Tasks</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>reported</td>
      <td>Tasks Reported, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>resolved</td>
      <td>Tasks Resolved, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>outstanding</td>
      <td>Tasks Outstanding, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>mttr</td>
      <td>Mean Time to Respond, TEAMS Tasks (days)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>over45</td>
      <td>Tasks Outstanding Over 45 Days, TEAMS</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>tpri</td>
      <td>Tasks by Priority, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>tsou</td>
      <td>Tasks by Source, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>tsub</td>
      <td>Tasks by Subcategory, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>ttyp</td>
      <td>Tasks by Type, TEAMS</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>bpsi</td>
      <td>Bike Ped Safety Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>cri</td>
      <td>Crash Rate Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>rsi</td>
      <td>Road Safety Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>flash</td>
      <td>Flash Events</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>kabco</td>
      <td>KABCO Safety Score</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>maint</td>
      <td>Maintenance Health Scores</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>ops</td>
      <td>Operations Health Scores</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>safety</td>
      <td>Safety Health Scores</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>vpd</td>
      <td>Vehicular Traffic Volume (veh/day)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>vph</td>
      <td>Vehicular Traffic Volume (veh/hr)</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>vphpa</td>
      <td>AM Peak Vehicular Traffic Volume (veh/hr)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>vphpp</td>
      <td>PM Peak Vehicular Traffic Volume (veh/hr)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>papd</td>
      <td>Pedestrian Actuations Per Day</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td>x</td>
    </tr>
    <tr>
      <td>aogd</td>
      <td>Arrivals on Green (%)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>aogh</td>
      <td>Arrivals on Green by hour (%)</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>pd</td>
      <td>Pedestrian Delay (minutes)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td>x</td>
    </tr>
    <tr>
      <td>prd</td>
      <td>Progression Radio</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>prh</td>
      <td>Progression Ratio by hour</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>qsd</td>
      <td>Queue Spillback Rate (%)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>qsh</td>
      <td>Queue Spillback Rate by hour (%)</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>sfd</td>
      <td>Split Failure Rate (%)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>sfh</td>
      <td>Split Failure Rate by Hour (%)</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>sfo</td>
      <td>Off-Peak Split Failure Rate by day (%)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>tp</td>
      <td>Vehicular Throughput (veh/hr)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td>x</td>
    </tr>
    <tr>
      <td>tti</td>
      <td>Travel Time Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>ttih</td>
      <td>Hourly Travel Time Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>pti</td>
      <td>Planning Time Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>ptih</td>
      <td>Hourly Planning Time Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>bi</td>
      <td>Buffer Index</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>bih</td>
      <td>Buffer Index by hour</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>spd</td>
      <td>Average Speed, HERE (mph)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>spdh</td>
      <td>Average Speed by hour, HERE (mph)</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>hourly_udc</td>
      <td>Hourly User Delay Costs</td>
      <td></td>
      <td></td>
      <td></td>
      <td>x</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
";
    }
}
