export const environment = {
  production: true,
  API_PATH: 'https://mlx49he5y5.execute-api.us-east-1.amazonaws.com/prod/',
  mapCenterLat: 33.757776,
  mapCenterLon: -84.391578,
  hasPageOperations: true,
  hasPageMaintenance: true,
  hasPageWatchdog: true,
  hasPageTeamsTasks: true,
  hasPageReports: true,
  hasPageHealthMetrics: true,
  hasPageSummaryTrend: true,
  hasBtnContactUs: true,
  hasBtnGdotApplications: true,
  ttiGoal: 1.2,
  ptiGoal: 1.3,
  duGoal: 0.95,
  ppuGoal: 0.95,
  cctvGoal: 0.95,
  cuGoal: 0.95,
};
