export interface IAppConfig {
  production: boolean,
  API_PATH: string,
  mapCenterLat: number,
  mapCenterLon: number,
  hasPageOperations: boolean,
  hasPageMaintenance: boolean,
  hasPageWatchdog: boolean,
  hasPageTeamsTasks: boolean,
  hasPageReports: boolean,
  hasPageHealthMetrics: boolean,
  hasBtnContactUs: boolean,
  hasBtnGdotApplications: boolean,
  hasPageSummaryTrend: boolean,
  ttiGoal: number,
  ptiGoal: number,
  duGoal: number,
  ppuGoal: number,
  cctvGoal: number,
  cuGoal: number,
}
